export const SeoFaq = () => {
  const faqs = [
    { q: "What does Hinton Studios produce?", a: "Hinton Studios is a Bengaluru-based AI filmmaking studio producing commercials, AI feature films, brand and product films, animation and vertical micro-dramas with human creative direction." },
    { q: "Who makes AI generated TVCs for brands in India?", a: "Hinton Studios produces AI generated TVCs for Indian and global brands, replacing conventional agency network pipelines with faster, AI-executed production." },
    { q: "How much does an AI ad film cost in India in 2026?", a: "The cost depends on duration, visual complexity, product accuracy, language versions and revision rounds. Share your brief for a scoped estimate; AI production still requires direction, editing and finishing." },
    { q: "Can I make a TV commercial entirely with AI?", a: "Yes. Using a combination of AI models like Veo, Sora, and Kling directed by human filmmakers, you can produce a 4K broadcast-quality TV commercial entirely with AI." },
    { q: "Is there an AI film studio in Bangalore?", a: "Yes, Hinton Studios is an AI film studio based in Bengaluru (Bangalore), serving brands across India, the US, and the Gulf." },
    { q: "What is the turnaround time for an AI ad film?", a: "Timelines depend on the brief, asset readiness, review rounds and finishing requirements. We agree a schedule after reviewing your script, references and delivery formats." },
    { q: "How do AI film studios keep characters consistent across shots?", a: "We maintain character consistency using advanced prompt engineering, custom model fine-tuning, and human-led VFX compositing across every generated frame." },
    { q: "What does human-directed AI-executed mean?", a: "Human-directed AI-executed means that while the raw frames are generated by AI pipelines, the creative vision, script, shot selection, and final grade are strictly controlled by human filmmakers." },
  ];

  return (
    <section className="bg-black text-white py-[10vmin] px-[6vmin] border-t border-white/10" aria-label="FAQ">
      <div className="max-w-7xl mx-auto">
        <h2 className="text-[4vmin] max-sm:text-[24px] font-light mb-[6vmin]">Frequently Asked Questions</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {faqs.map((faq, i) => (
            <div key={i}>
              <h3 className="text-[2vmin] max-sm:text-[16px] font-medium mb-2">{faq.q}</h3>
              <p className="text-[1.6vmin] max-sm:text-[14px] text-white/70 leading-relaxed">{faq.a}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
